spring:
  application:
    name: spring-data-elasticsearch-demo
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout: 1s
          username:
          password:
          socket-timeout: 5s
          use-ssl: false
  elasticsearch:
    jest:
      connection-timeout: 3s
      multi-threaded: true
      username:
      password:
        proxy:
          host:
          port:
      read-timeout: 3s
    rest:
      connection-timeout: 1s
      username:
      password:
      read-timeout: 30s
      uris: http://10.147.20.227:9200
logging:
  level:
    root: INFO
    com.engrz.demo.spring: DEBUG